### ISSUE TITLE
Set GitHub PAT permanently on AWS-Lightsail

### ISSUE THREAD

**Issue by Tazinho** [r-lib/credentials#18]
I am using `credentials::set_github_pat()` on AWS-Lightsail (Ubuntu, personal User) and it works basically fine.

However, when I restart the instance, RStudio asks me again for PW/User.

Also if I run `credentials::set_github_pat()` after restart, I am getting asked for the PAT again.

Is there a way around this and set the PAT permanently? What could be the issue?

Edit: Also writing `credentials::set_github_pat()` into .Renviron as recommended in this blogpost https://ropensci.org/blog/2020/07/07/github-pat/ doesn't solve this and instead leads to the following error msg. in RStudioServer after a reboot.

![grafik](https://user-images.githubusercontent.com/11295192/128028777-e72ae500-05a9-4f21-91a6-adc184c7a77a.png)

**Comment by jeroen** [comment]
You need to set a credential helper other than cache.

Op di 3 aug. 2021 15:48 schreef Malte Grosser ***@***.***>:

**Comment by jennybc** [comment]
This is a tricky problem (which I have also encountered on RStudio Server), because linux doesn't have an OS-level store like macOS Keychain or Windows Credential Manager. I think you might need to use the `.Renviron` solution.

But it sounds like you're mis-implementing that. `.Renviron` can only contain a `NAME=VALUE` type of entry for storing your PAT in an env var. Whereas your error message makes it look like you're trying to **run R code** from `.Renviron`, which you can't. (That can happen in `.Rprofile`.)

**Comment by Tazinho** [comment]
Thanks to both of you!

Setting `credentials::credential_helper_set("store")` indeed solved the issue in my case.
